### ISSUE TITLE
Add gitter link to README for discussion

### ISSUE THREAD

**Issue by vjpr** [jpillora/debator#1]

**Comment by jpillora** [comment]
Hey vaugh, that was a quick spot! I'm in the process of putting all my ideas into the README, will create a gitter right after that :)

**Comment by vjpr** [comment]
Just opened up github activity feed randomly and there it was!

**Comment by jpillora** [comment]
So weird, first time thinking about this is ages, just happened to come up in conversation with a friend this morning

**Comment by vjpr** [comment]
Yeh I haven't thought about it for ages. Its so necessary. I had a crack a few years ago, but its a tough problem.

**Comment by vjpr** [comment]
Open up a private gitter room if you want to bounce some ideas around...

**Comment by jpillora** [comment]
Done https://gitter.im/jpillora/debator

Checkout the [README](https://github.com/jpillora/debator) first and we'll chat, just heading out an hour
